# Generated by Django 4.2 on 2023-04-19 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("registro_de_animal", "0002_author_category_post_delete_taskitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("idade", models.IntegerField()),
                ("data_nascimento", models.DateField()),
                ("data_cadastro", models.DateField(auto_now_add=True)),
                ("cor", models.CharField(max_length=50)),
                ("foto", models.ImageField(upload_to="")),
                ("rga", models.CharField(max_length=50)),
                ("castrado", models.BooleanField()),
                ("anilha", models.CharField(max_length=50)),
                ("chip", models.CharField(max_length=50)),
                ("vacinado", models.BooleanField()),
                ("vermifugado", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Porte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Raça",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Sexo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name="Category",
            new_name="Especie",
        ),
        migrations.RenameModel(
            old_name="Author",
            new_name="Tutor",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
        migrations.AddField(
            model_name="animal",
            name="especie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="registro_de_animal.especie",
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="porte",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="registro_de_animal.porte",
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="raça",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="registro_de_animal.raça",
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="sexo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="registro_de_animal.sexo",
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="tutor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="registro_de_animal.tutor",
            ),
        ),
    ]
