# Generated by Django 4.2 on 2023-04-19 14:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "registro_de_animal",
            "0003_animal_porte_raça_sexo_rename_category_especie_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="especie",
            old_name="title",
            new_name="nome",
        ),
        migrations.RenameField(
            model_name="porte",
            old_name="title",
            new_name="nome",
        ),
        migrations.RenameField(
            model_name="raça",
            old_name="title",
            new_name="nome",
        ),
        migrations.RenameField(
            model_name="sexo",
            old_name="title",
            new_name="nome",
        ),
        migrations.RenameField(
            model_name="tutor",
            old_name="User",
            new_name="nome",
        ),
    ]
