# Generated by Django 4.2 on 2023-04-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_de_animal', '0004_rename_title_especie_nome_rename_title_porte_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('vac_id', models.AutoField(primary_key=True, serialize=False)),
                ('vac_nome', models.CharField(max_length=50)),
                ('vac_data_admin', models.DateField(auto_now_add=True)),
                ('vac_num_dose', models.IntegerField()),
                ('vac_fabricante', models.CharField(max_length=50)),
                ('vac_validade', models.DateField(auto_now_add=True)),
                ('animal_id', models.CharField(max_length=50)),
            ],
        ),
    ]
