# Generated by Django 4.2 on 2023-04-22 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro_de_animal', '0005_vacina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacina',
            name='animal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro_de_animal.animal'),
        ),
    ]
