# Generated by Django 4.2 on 2023-04-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_de_animal', '0006_alter_vacina_animal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacina',
            name='vac_data_admin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vacina',
            name='vac_validade',
            field=models.DateField(),
        ),
    ]
