# Generated by Django 4.2 on 2023-05-09 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_de_animal', '0007_alter_vacina_vac_data_admin_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vacina',
        ),
    ]
