# Generated by Django 4.2 on 2023-05-09 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registro_de_animal', '0008_delete_vacina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('vac_id', models.AutoField(primary_key=True, serialize=False)),
                ('vac_nome', models.CharField(max_length=50)),
                ('vac_data_admin', models.DateField()),
                ('vac_num_dose', models.IntegerField()),
                ('vac_fabricante', models.CharField(max_length=50)),
                ('vac_validade', models.DateField()),
                ('animal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro_de_animal.animal')),
            ],
        ),
    ]
