# Generated by Django 4.2 on 2023-05-09 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro_de_animal', '0008_delete_vacina'),
        ('saude_do_animal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('med_id', models.AutoField(primary_key=True, serialize=False)),
                ('med_nome', models.CharField(max_length=50)),
                ('med_dosagem', models.CharField(max_length=50)),
                ('med_freq_admin', models.CharField(max_length=50)),
                ('med_duracao', models.CharField(max_length=50)),
                ('med_motivo_uso', models.CharField(max_length=150)),
                ('animal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro_de_animal.animal')),
            ],
        ),
    ]
